In [1]:
import pandas as pd
import numpy as np

In [2]:
products=pd.read_csv("amazon_products.csv")

In [3]:
products.head(1)

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.0,104,False,2000

In [4]:
products.isnull().sum()

asin                 0
title                1
imgUrl               0
productURL           0
stars                0
reviews              0
price                0
listPrice            0
category_id          0
isBestSeller         0
boughtInLastMonth    0
dtype: int64

In [5]:
products.describe()

,stars,reviews,price,listPrice,category_id,boughtInLastMonth
count,1.426337e+06,1.426337e+06,1.426337e+06,1.426337e+06,1.426337e+06,1.426337e+06
mean,3.999512e+00,1.807508e+02,4.337540e+01,1.244916e+01,1.237409e+02,1.419823e+02
std,1.344292e+00,1.761453e+03,1.302893e+02,4.611198e+01,7.311273e+01,8.362720e+02
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
25%,4.100000e+00,0.000000e+00,1.199000e+01,0.000000e+00,6.500000e+01,0.000000e+00
50%,4.400000e+00,0.000000e+00,1.995000e+01,0.000000e+00,1.200000e+02,0.000000e+00
75%,4.600000e+00,0.000000e+00,3.599000e+01,0.000000e+00,1.760000e+02,5.000000e+01
max,5.000000e+00,3.465630e+05,1.973181e+04,9.999900e+02,2.700000e+02,1.000000e+05

In [6]:
products.fillna("product_title",inplace=True)

In [7]:
products.isnull().sum()

asin                 0
title                0
imgUrl               0
productURL           0
stars                0
reviews              0
price                0
listPrice            0
category_id          0
isBestSeller         0
boughtInLastMonth    0
dtype: int64

In [8]:
# title, imageURL, productURL, stars, price, category_id

In [9]:
products.head(1)

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.0,104,False,2000

In [10]:
products=products[["title", "imgUrl", "productURL", "stars", "price", "category_id"]]

In [11]:
products.head(1)

,title,imgUrl,productURL,stars,price,category_id
0,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,139.99,104

In [12]:
products=products[["title", "imgUrl", "productURL", "stars", "price", "category_id"]]

In [13]:
products.head(1)

,title,imgUrl,productURL,stars,price,category_id
0,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,139.99,104

In [14]:
products.rename(columns={"imgUrl":'imgurl','productURL':'producturl','category_id':'id'},inplace=True)

In [15]:
products.head(1)

,title,imgurl,producturl,stars,price,id
0,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,139.99,104

In [16]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426337 entries, 0 to 1426336
Data columns (total 6 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   title       1426337 non-null  object
 1   imgurl      1426337 non-null  object
 2   producturl  1426337 non-null  object
 3   stars       1426337 non-null  float64
 4   price       1426337 non-null  float64
 5   id          1426337 non-null  int64
dtypes: float64(2), int64(1), object(3)
memory usage: 65.3+ MB

In [17]:
products['stars'].astype(float)

0          4.5
1          4.5
2          4.6
3          4.6
4          4.5
          ...
1426332    4.2
1426333    4.4
1426334    3.6
1426335    4.5
1426336    4.9
Name: stars, Length: 1426337, dtype: float64

In [18]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426337 entries, 0 to 1426336
Data columns (total 6 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   title       1426337 non-null  object
 1   imgurl      1426337 non-null  object
 2   producturl  1426337 non-null  object
 3   stars       1426337 non-null  float64
 4   price       1426337 non-null  float64
 5   id          1426337 non-null  int64
dtypes: float64(2), int64(1), object(3)
memory usage: 65.3+ MB

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
import pandas as pd

# --------------------------
# Step 1: Prepare the data
# --------------------------
# Make sure there are no missing product titles
products['title'] = products['title'].fillna('')

# Convert 'stars' column to numbers so we can sort later
products['stars'] = pd.to_numeric(products['stars'], errors='coerce').fillna(0)

# --------------------------
# Step 2: Convert titles to TF-IDF vectors
# --------------------------
# TF-IDF converts text into numbers for comparison
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_features=2000)
tfidf_matrix = tfidf_vectorizer.fit_transform(products['title'])

# --------------------------
# Step 3: Train NearestNeighbors model
# --------------------------
# This will help us find similar products quickly
nn_model = NearestNeighbors(n_neighbors=10, metric='cosine', algorithm='brute')
nn_model.fit(tfidf_matrix)

# --------------------------
# Step 4: Function to recommend products
# --------------------------
def recommend_products(search_title, num_recommendations=5):
    # Step 4a: Find the product row that matches the search
    matched_products = products[products['title'].str.contains(search_title, case=False, na=False)]
    
    if matched_products.empty:
        return "Product not found"
    
    # Take the first product that matches the search
    product_index = matched_products.index[0]
    
    # Step 4b: Find similar products using NearestNeighbors
    distances, similar_indices = nn_model.kneighbors(tfidf_matrix[product_index], n_neighbors=num_recommendations+1)
    
    # Step 4c: Flatten the indices array and remove the searched product itself
    similar_indices = similar_indices.flatten()
    similar_indices = [i for i in similar_indices if i != product_index][:num_recommendations]
    
    # Step 4d: Select recommended products and sort by rating (stars) descending
    recommended_products = products.iloc[similar_indices].sort_values(by='stars', ascending=False)
    
    # Step 4e: Return only useful columns
    return recommended_products[['title', 'imgurl', 'producturl', 'stars', 'price']]

In [ ]:
recommend_products('Bags')

In [ ]:
products['producturl'][130]

In [ ]:
products.head(1)

In [ ]:
products.shape()